export const cooperatives = [
  {
    id: 'okafor-farmers-thrift',
    name: 'Okafor Farmers Thrift & Credit',
    registrationNumber: '2024-X99',
    state: 'Lagos',
    cooperativeType: 'thrift',
    memberCount: 1248,
    balance: 48200050,
    healthScore: 92,
    nombaVirtualAccountRef: 'VA-OF-2049',
    nombaAccountId: 'ACCT-4491',
  },
];

export const members = [
  { id: 'mem-01', firstName: 'Amina', lastName: 'Okafor', role: 'treasurer', bvnVerified: true },
  { id: 'mem-02', firstName: 'Bola', lastName: 'Adewale', role: 'executive1', bvnVerified: true },
  { id: 'mem-03', firstName: 'Chika', lastName: 'Nwosu', role: 'executive2', bvnVerified: true },
];

export const dashboard = {
  balance: 482000.5,
  nextContribution: 'Jan 15, ₦20,000',
  tenure: '14 Months Active',
  trustScore: 92,
  loanStatus: 'Eligible',
  activityFeed: [
    { id: 'feed-1', title: 'New Member Joined', text: 'Adewale K. joined the Lagos Mainland cell.', time: '2 mins ago' },
    { id: 'feed-2', title: 'Dividend Payout', text: 'Quarterly 4% dividends distributed to active members.', time: '1 hour ago' },
    { id: 'feed-3', title: 'General Meeting', text: 'Annual review scheduled for Jan 20th.', time: '5 hours ago' },
    { id: 'feed-4', title: 'Identity Verified', text: 'KYC documents were re-verified by Admin #04.', time: 'Yesterday' },
  ],
  contributionTrend: [18, 21, 19, 24, 26, 23, 29, 35, 40, 44, 49, 53],
  contributionHistory: [
    { id: 'txn-9921-xf', date: '2023-12-15', amount: 20000, status: 'confirmed', reference: 'TXN-9921-XF' },
    { id: 'txn-8742-lk', date: '2023-11-15', amount: 20000, status: 'confirmed', reference: 'TXN-8742-LK' },
    { id: 'txn-4410-pp', date: '2023-10-15', amount: 20000, status: 'archived', reference: 'TXN-4410-PP' },
    { id: 'txn-3291-zz', date: '2023-09-15', amount: 25000, status: 'confirmed', reference: 'TXN-3291-ZZ' },
  ],
};

export const withdrawalQueue = [
  {
    id: 'wf-9042',
    ref: '#WF-9042',
    initiated: '24/10/23',
    recipient: 'Agba Ventures Ltd',
    amount: 2450000,
    sigs: '■■□',
    status: 'processing',
    destinationAccount: '0123456789',
    destinationBankCode: '058',
    purpose: 'Equipment procurement for Q4 distribution run.',
    requestedBy: 'Amina Okafor',
    signatureCount: 1,
    average30d: 510000,
    riskScore: 0.41,
    explanations: ['Amount is 3.8x the rolling 30-day average', 'Only 1 of 3 required signatures present'],
  },
  {
    id: 'wf-9038',
    ref: '#WF-9038',
    initiated: '23/10/23',
    recipient: 'Staff Gratuity Fund',
    amount: 12000000,
    sigs: '■■■',
    status: 'flagged: risk',
    destinationAccount: '0987654321',
    destinationBankCode: '050',
    purpose: 'Year-end staff benefit disbursement.',
    requestedBy: 'Amina Okafor',
    signatureCount: 3,
    average30d: 1200000,
    riskScore: 0.89,
    explanations: ['Requested amount is unusually high for the cooperative profile', 'Historical pattern shows rapid growth in payout size'],
  },
  {
    id: 'wf-8991',
    ref: '#WF-8991',
    initiated: '21/10/23',
    recipient: 'Property Rent (H2)',
    amount: 850000,
    sigs: '■□□',
    status: 'pending sig',
    destinationAccount: '0222333444',
    destinationBankCode: '044',
    purpose: 'Office rent settlement for second half of the year.',
    requestedBy: 'Amina Okafor',
    signatureCount: 1,
    average30d: 510000,
    riskScore: 0.24,
    explanations: ['Amount is within the normal historical range', 'Awaiting two additional signatures'],
  },
];

export const alerts = [
  {
    id: 'alert-01',
    type: 'anomaly',
    title: 'Large withdrawal outside baseline',
    reason: 'Requested amount is 4.7x the 30-day average.',
    severity: 'High',
    riskScore: 0.87,
    evidence: {
      average30d: 510000,
      requested: 2450000,
      deviation: 4.7,
      signatures: 1,
      rule: 'withdrawal_amount_zscore',
    },
  },
  {
    id: 'alert-02',
    type: 'ghost_member',
    title: 'Duplicate BVN detected',
    reason: 'Same BVN appears across two active member profiles.',
    severity: 'Medium',
    riskScore: 0.65,
    evidence: {
      bvnHash: 'bvn:ae18f...19d',
      matches: 2,
      rule: 'duplicate_bvn_crosscheck',
    },
  },
  {
    id: 'alert-03',
    type: 'ring_detected',
    title: 'Repeated approval cluster',
    reason: 'Three requests were co-signed by the same trio in 9 days.',
    severity: 'High',
    riskScore: 0.78,
    evidence: {
      trio: ['mem-01', 'mem-02', 'mem-03'],
      repeatCount: 3,
      rule: 'approval_cluster_repetition',
    },
  },
];
